[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --ignore-scripts"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx tsc"
]

[start]
cmd = "npx prisma migrate deploy && node dist/server.js"
