import type { Lang, Currency } from '@/stores/appStore'

export type { Lang, Currency }

// ─── TRADUCTIONS LANDING ──────────────────────────────────────────────────────

export const LANDING_TRANSLATIONS = {
  fr: {
    nav: ['Fonctionnalités', 'Tarifs', 'FAQ'],
    nav_features: 'Fonctionnalités',
    nav_pricing: 'Tarifs',
    nav_faq: 'FAQ',
    nav_login: 'Connexion',
    badge: "N°1 en Afrique francophone · Sénégal · Côte d'Ivoire · Mali · Burkina",
    h1a: 'Gérez votre boutique en Afrique',
    h1b: 'Caisse, stock, clients & RH en un seul logiciel',
    hero_sub: "HabaShop est le logiciel de gestion commerciale tout-en-un pour les boutiques et superettes d'Afrique : caisse (POS), gestion de stock, clients, RH et analytics — rapide et disponible même sans internet.",
    cta1: 'Démarrer gratuitement',
    cta2: 'Voir la démo',
    stat1_l: 'Modules intégrés',
    stat2_l: 'Offline-ready',
    stat3_l: 'Devises supportées',
    stat4_l: 'Pays cibles',
    features_label: 'FONCTIONNALITÉS',
    features_title: 'Tout ce dont vous avez besoin',
    features_sub: '16 modules intégrés pour gérer chaque aspect de votre commerce',
    feature1_title: 'Caisse Enregistreuse (POS)',
    feature1_desc: 'Encaissement rapide, catalogue filtrable, multi-modes de paiement, ticket imprimé ou WhatsApp, mode offline.',
    feature2_title: 'Gestion de Stock Temps Réel',
    feature2_desc: 'Alertes rupture en temps réel, CRUD produits, bon de commande automatique depuis la fiche produit.',
    feature3_title: 'Rapports & Analyses',
    feature3_desc: 'KPIs par période, CA, marges, top produits, répartition paiements. Exports CSV et PDF en un clic.',
    feature4_title: 'Gestion Clients & Fidélité',
    feature4_desc: "Fiches clients, types (gros/semi-gros/fidèle), programme de fidélité et historique d'achats complet.",
    feature5_title: 'Ressources Humaines & Paie',
    feature5_desc: 'Fiches employés, planning hebdomadaire drag & drop, gestion des congés et suivi des présences.',
    feature6_title: 'Sécurité & RBAC',
    feature6_desc: "Rôles et permissions granulaires, authentification 2FA TOTP, journal d'audit immuable, multi-tenant.",
    how_label: 'COMMENT ÇA MARCHE',
    how_title: 'Démarrez en 4 étapes',
    step1_title: 'Créez votre boutique',
    step1_desc: 'Inscription en 2 minutes. Configurez votre espace, ajoutez vos produits et votre équipe.',
    step2_title: 'Formez votre équipe',
    step2_desc: "Interface intuitive. Vos caissiers maîtrisent la caisse en moins d'une heure.",
    step3_title: 'Encaissez & gérez',
    step3_desc: 'POS rapide, gestion du stock en temps réel, alertes automatiques, rapports instantanés.',
    step4_title: 'Analysez & croissez',
    step4_desc: 'Tableaux de bord, exports, tendances produits. Prenez de meilleures décisions chaque jour.',
    testimonials_label: 'TÉMOIGNAGES',
    testimonials_title: 'Ils font confiance à HabaShop',
    test1_name: 'Mamadou Diallo',
    test1_role: 'Grossiste · Dakar',
    test1_quote: "Depuis HabaShop, j'ai une visibilité totale sur mon stock. Les alertes de rupture m'ont sauvé plusieurs fois.",
    test2_name: 'Fatou Koné',
    test2_role: 'Épicerie · Abidjan',
    test2_quote: "La caisse est ultra-rapide et fonctionne même quand internet coupe. Mes caissières ont été formées en 30 minutes.",
    test3_name: 'Ibrahim Touré',
    test3_role: 'Demi-grossiste · Bamako',
    test3_quote: "Les rapports de vente m'aident à prendre de meilleures décisions d'achat. L'interface est claire et les données sont toujours à jour.",
    pricing_label: 'TARIFS',
    pricing_title: "Des prix en Franc CFA, accessibles partout en Afrique",
    pricing_sub: "14 jours d'essai gratuit — payez par Wave, Orange Money ou MTN. Aucune carte requise.",
    per_month: '/mois',
    on_estimate: 'Sur devis',
    most_popular: 'Le plus populaire',
    free_start: 'Commencer gratuitement',
    try_free: 'Essayer 14 jours',
    contact_us: 'Nous contacter',
    starter_name: 'Starter',
    starter_sub: 'Pour les petits commerces',
    business_name: 'Business',
    business_sub: 'Pour les commerces en croissance',
    enterprise_name: 'Enterprise',
    enterprise_sub: 'Pour les réseaux de boutiques',
    feat_pos_1: 'Caisse POS (1 caisse)',
    feat_stock_500: 'Gestion stock (500 produits)',
    feat_reports: 'Rapports de base',
    feat_support: 'Support par email',
    feat_multiuser: 'Multi-utilisateurs',
    feat_hr: 'Module RH & Planning',
    feat_pos_3: 'Caisse POS (3 caisses)',
    feat_stock_inf: 'Stock illimité',
    feat_crm: 'CRM Clients complet',
    feat_hr_full: 'RH, Planning, Paie',
    feat_5users: '5 utilisateurs inclus',
    feat_priority: 'Support prioritaire',
    feat_pos_inf: 'Caisses illimitées',
    feat_multi_shop: 'Multi-boutiques',
    feat_users_inf: 'Utilisateurs illimités',
    feat_api: 'API dédiée',
    feat_onboarding: 'Onboarding sur site',
    feat_sla: 'SLA garanti 99,9 %',
    faq_label: 'FAQ',
    faq_title: 'Questions fréquentes',
    faq1_q: 'HabaShop fonctionne-t-il sans internet ?',
    faq1_a: "Oui ! La caisse POS fonctionne en mode offline grâce à la technologie PWA. Les ventes sont stockées localement et synchronisées automatiquement au retour de la connexion.",
    faq2_q: "Quels modes de paiement sont acceptés pour s'abonner ?",
    faq2_a: "HabaShop accepte Wave, Orange Money, MTN Money, virement bancaire et carte bancaire. Aucune carte internationale n'est requise.",
    faq3_q: 'Combien coûte HabaShop ?',
    faq3_a: "HabaShop propose un essai gratuit de 14 jours. Le plan Starter coûte 14 400 F CFA/mois, le plan Business 34 750 F CFA/mois, et le plan Enterprise est sur devis.",
    faq4_q: "HabaShop est-il disponible en Côte d'Ivoire, au Mali et au Burkina Faso ?",
    faq4_a: "Oui, HabaShop est disponible dans toute l'Afrique francophone : Sénégal, Côte d'Ivoire, Mali, Burkina Faso, Guinée, Cameroun, Congo, Gabon, Togo, Bénin et plus de 150 pays.",
    faq5_q: 'Puis-je importer mes produits existants dans HabaShop ?',
    faq5_a: "Oui, HabaShop permet l'import de produits via fichier CSV ou Excel. L'équipe support peut vous accompagner dans la migration depuis votre ancien système.",
    cta_title: 'Prêt à moderniser votre commerce ?',
    cta_sub: "Rejoignez les commerçants d'Afrique qui font confiance à HabaShop",
    cta_btn: "Commencer maintenant — C'est gratuit",
    cta_note: "Aucune carte bancaire requise · 14 jours d'essai gratuit",
    footer: '© 2026 HabaShop · Logiciel SaaS pour commerces africains',
    footer_links: ['Confidentialité', 'CGU', 'Contact'],
    trust_title: "Déjà actifs au Sénégal, en Côte d'Ivoire, au Mali et 8+ pays africains",
    cur_title: 'Multi-devises & Multi-langues',
    cur_sub: 'Adapté à votre marché, dans votre langue',
    proof_stores: 'boutiques actives (Sénégal, CI, Mali)',
    proof_countries: '150+ pays',
  },
  en: {
    nav: ['Features', 'Pricing', 'FAQ'],
    nav_features: 'Features',
    nav_pricing: 'Pricing',
    nav_faq: 'FAQ',
    nav_login: 'Sign in',
    badge: 'Built for francophone Africa',
    h1a: 'Manage your business',
    h1b: 'simply and efficiently',
    hero_sub: 'HabaShop centralizes your POS, inventory, team and finances in one tool — simple, fast, and available even without internet.',
    cta1: 'Start for free',
    cta2: 'View demo',
    stat1_l: 'Integrated modules',
    stat2_l: 'Offline-ready',
    stat3_l: 'Supported currencies',
    stat4_l: 'Target countries',
    features_label: 'FEATURES',
    features_title: 'Everything you need',
    features_sub: '16 integrated modules to manage every aspect of your business',
    feature1_title: 'Point of Sale',
    feature1_desc: 'Fast checkout, filterable catalog, multi-payment modes, printed or WhatsApp receipt, offline mode.',
    feature2_title: 'Stock & Inventory',
    feature2_desc: 'Real-time stock alerts, product CRUD, automatic purchase order from product sheet.',
    feature3_title: 'Reports & Analytics',
    feature3_desc: 'KPIs by period, revenue, margins, top products, payment breakdown. CSV and PDF exports in one click.',
    feature4_title: 'CRM Customers',
    feature4_desc: 'Customer profiles, types (wholesale/loyal), loyalty program and full purchase history.',
    feature5_title: 'HR & Scheduling',
    feature5_desc: 'Employee profiles, drag & drop weekly schedule, leave management and attendance tracking.',
    feature6_title: 'Security & RBAC',
    feature6_desc: 'Granular roles and permissions, 2FA TOTP authentication, immutable audit log, multi-tenant.',
    how_label: 'HOW IT WORKS',
    how_title: 'Get started in 4 steps',
    step1_title: 'Create your store',
    step1_desc: 'Sign up in 2 minutes. Set up your workspace, add your products and team.',
    step2_title: 'Train your team',
    step2_desc: 'Intuitive interface. Your cashiers master the POS in less than an hour.',
    step3_title: 'Sell & manage',
    step3_desc: 'Fast POS, real-time inventory, automatic alerts, instant reports.',
    step4_title: 'Analyze & grow',
    step4_desc: 'Dashboards, exports, product trends. Make better decisions every day.',
    testimonials_label: 'TESTIMONIALS',
    testimonials_title: 'They trust HabaShop',
    test1_name: 'Mamadou Diallo',
    test1_role: 'Wholesaler · Dakar',
    test1_quote: "Since HabaShop, I have total visibility over my stock. The out-of-stock alerts have saved me several times.",
    test2_name: 'Fatou Koné',
    test2_role: 'Grocery · Abidjan',
    test2_quote: "The POS is ultra-fast and works even when the internet cuts out. My cashiers were trained in 30 minutes.",
    test3_name: 'Ibrahim Touré',
    test3_role: 'Semi-wholesaler · Bamako',
    test3_quote: "Sales reports help me make better purchasing decisions. The interface is clear and data is always up to date.",
    pricing_label: 'PRICING',
    pricing_title: 'Prices adapted for Africa',
    pricing_sub: '14-day free trial — no credit card required',
    per_month: '/mo',
    on_estimate: 'Custom quote',
    most_popular: 'Most popular',
    free_start: 'Start for free',
    try_free: 'Try 14 days',
    contact_us: 'Contact us',
    starter_name: 'Starter',
    starter_sub: 'For small businesses',
    business_name: 'Business',
    business_sub: 'For growing businesses',
    enterprise_name: 'Enterprise',
    enterprise_sub: 'For store networks',
    feat_pos_1: 'POS (1 register)',
    feat_stock_500: 'Stock management (500 products)',
    feat_reports: 'Basic reports',
    feat_support: 'Email support',
    feat_multiuser: 'Multi-user',
    feat_hr: 'HR & Scheduling module',
    feat_pos_3: 'POS (3 registers)',
    feat_stock_inf: 'Unlimited stock',
    feat_crm: 'Full CRM',
    feat_hr_full: 'HR, Scheduling, Payroll',
    feat_5users: '5 users included',
    feat_priority: 'Priority support',
    feat_pos_inf: 'Unlimited registers',
    feat_multi_shop: 'Multi-store',
    feat_users_inf: 'Unlimited users',
    feat_api: 'Dedicated API',
    feat_onboarding: 'On-site onboarding',
    feat_sla: '99.9% SLA guarantee',
    faq_label: 'FAQ',
    faq_title: 'Frequently asked questions',
    faq1_q: 'Does HabaShop work without internet?',
    faq1_a: 'Yes! The POS works offline thanks to PWA technology. Sales are stored locally and automatically synced when the connection returns.',
    faq2_q: 'Which payment methods are accepted to subscribe?',
    faq2_a: 'HabaShop accepts Wave, Orange Money, MTN Money, bank transfer and credit card. No international card required.',
    faq3_q: 'How much does HabaShop cost?',
    faq3_a: 'HabaShop offers a 14-day free trial. The Starter plan is 14,400 F CFA/month, Business is 34,750 F CFA/month, and Enterprise is on a custom quote.',
    faq4_q: "Is HabaShop available in Côte d'Ivoire, Mali and Burkina Faso?",
    faq4_a: "Yes, HabaShop is available across French-speaking Africa: Senegal, Côte d'Ivoire, Mali, Burkina Faso, Guinea, Cameroon, Congo, Gabon, Togo, Benin and 150+ countries.",
    faq5_q: 'Can I import my existing products into HabaShop?',
    faq5_a: 'Yes, HabaShop lets you import products via CSV or Excel file. The support team can help you migrate from your previous system.',
    cta_title: 'Ready to modernize your business?',
    cta_sub: 'Join African merchants who trust HabaShop',
    cta_btn: "Start now — It's free",
    cta_note: 'No credit card required · 14-day free trial',
    footer: '© 2026 HabaShop · SaaS software for African businesses',
    footer_links: ['Privacy', 'Terms', 'Contact'],
    trust_title: 'Already active in 8+ African countries',
    cur_title: 'Multi-currency & Multi-language',
    cur_sub: 'Tailored to your market, in your language',
    proof_stores: 'active stores',
    proof_countries: '150+ countries',
  },
  es: {
    nav: ['Funciones', 'Precios', 'FAQ'],
    nav_features: 'Funciones',
    nav_pricing: 'Precios',
    nav_faq: 'FAQ',
    nav_login: 'Iniciar sesión',
    badge: 'Diseñado para el África francófona',
    h1a: 'Gestiona tu negocio',
    h1b: 'de forma simple y eficiente',
    hero_sub: 'HabaShop centraliza tu caja, inventario, equipo y finanzas en una sola herramienta — simple, rápida y disponible incluso sin internet.',
    cta1: 'Empezar gratis',
    cta2: 'Ver demo',
    stat1_l: 'Módulos integrados',
    stat2_l: 'Offline-ready',
    stat3_l: 'Divisas admitidas',
    stat4_l: 'Países objetivo',
    features_label: 'FUNCIONES',
    features_title: 'Todo lo que necesitas',
    features_sub: '16 módulos integrados para gestionar cada aspecto de tu negocio',
    feature1_title: 'Punto de Venta',
    feature1_desc: 'Cobro rápido, catálogo filtrable, múltiples modos de pago, ticket impreso o por WhatsApp, modo offline.',
    feature2_title: 'Stock e Inventario',
    feature2_desc: 'Alertas de rotura en tiempo real, CRUD de productos, pedido automático desde la ficha de producto.',
    feature3_title: 'Informes y Análisis',
    feature3_desc: 'KPIs por período, ingresos, márgenes, top productos, desglose de pagos. Exportaciones CSV y PDF en un clic.',
    feature4_title: 'CRM Clientes',
    feature4_desc: 'Fichas de clientes, tipos (mayorista/fiel), programa de fidelidad e historial completo de compras.',
    feature5_title: 'RRHH y Horarios',
    feature5_desc: 'Fichas de empleados, horario semanal drag & drop, gestión de bajas y seguimiento de asistencia.',
    feature6_title: 'Seguridad y RBAC',
    feature6_desc: 'Roles y permisos granulares, autenticación 2FA TOTP, registro de auditoría inmutable, multi-tenant.',
    how_label: 'CÓMO FUNCIONA',
    how_title: 'Empieza en 4 pasos',
    step1_title: 'Crea tu tienda',
    step1_desc: 'Regístrate en 2 minutos. Configura tu espacio, añade tus productos y equipo.',
    step2_title: 'Forma a tu equipo',
    step2_desc: 'Interfaz intuitiva. Tus cajeros dominan el POS en menos de una hora.',
    step3_title: 'Vende y gestiona',
    step3_desc: 'POS rápido, inventario en tiempo real, alertas automáticas, informes instantáneos.',
    step4_title: 'Analiza y crece',
    step4_desc: 'Paneles, exportaciones, tendencias de productos. Toma mejores decisiones cada día.',
    testimonials_label: 'TESTIMONIOS',
    testimonials_title: 'Confían en HabaShop',
    test1_name: 'Mamadou Diallo',
    test1_role: 'Mayorista · Dakar',
    test1_quote: "Desde HabaShop, tengo visibilidad total sobre mi stock. Las alertas de rotura me han salvado varias veces.",
    test2_name: 'Fatou Koné',
    test2_role: 'Colmado · Abiyán',
    test2_quote: "La caja es ultrarrápida y funciona incluso cuando se corta internet. Mis cajeras se formaron en 30 minutos.",
    test3_name: 'Ibrahim Touré',
    test3_role: 'Semi-mayorista · Bamako',
    test3_quote: "Los informes de ventas me ayudan a tomar mejores decisiones de compra. La interfaz es clara y los datos siempre están al día.",
    pricing_label: 'PRECIOS',
    pricing_title: 'Precios adaptados para África',
    pricing_sub: '14 días de prueba gratuita — sin tarjeta requerida',
    per_month: '/mes',
    on_estimate: 'Presupuesto',
    most_popular: 'El más popular',
    free_start: 'Empezar gratis',
    try_free: 'Probar 14 días',
    contact_us: 'Contáctanos',
    starter_name: 'Starter',
    starter_sub: 'Para pequeños negocios',
    business_name: 'Business',
    business_sub: 'Para negocios en crecimiento',
    enterprise_name: 'Enterprise',
    enterprise_sub: 'Para redes de tiendas',
    feat_pos_1: 'POS (1 caja)',
    feat_stock_500: 'Gestión stock (500 productos)',
    feat_reports: 'Informes básicos',
    feat_support: 'Soporte por email',
    feat_multiuser: 'Multi-usuario',
    feat_hr: 'Módulo RRHH y Horarios',
    feat_pos_3: 'POS (3 cajas)',
    feat_stock_inf: 'Stock ilimitado',
    feat_crm: 'CRM completo',
    feat_hr_full: 'RRHH, Horarios, Nóminas',
    feat_5users: '5 usuarios incluidos',
    feat_priority: 'Soporte prioritario',
    feat_pos_inf: 'Cajas ilimitadas',
    feat_multi_shop: 'Multi-tienda',
    feat_users_inf: 'Usuarios ilimitados',
    feat_api: 'API dedicada',
    feat_onboarding: 'Onboarding en sitio',
    feat_sla: 'SLA garantizado 99,9 %',
    faq_label: 'FAQ',
    faq_title: 'Preguntas frecuentes',
    faq1_q: '¿HabaShop funciona sin internet?',
    faq1_a: '¡Sí! La caja POS funciona offline gracias a la tecnología PWA. Las ventas se almacenan localmente y se sincronizan automáticamente al recuperar la conexión.',
    faq2_q: '¿Cuánto tarda la instalación?',
    faq2_a: '¡No requiere instalación! HabaShop es una aplicación web (SaaS). Te conectas desde cualquier navegador. La configuración inicial lleva menos de 30 minutos.',
    faq3_q: '¿Cuánto cuesta HabaShop?',
    faq3_a: 'HabaShop ofrece una prueba gratuita de 14 días. El plan Starter cuesta 14 400 F CFA/mes, el plan Business 34 750 F CFA/mes, y el plan Enterprise es a medida (bajo presupuesto).',
    faq4_q: '¿Puedo gestionar varias tiendas?',
    faq4_a: 'Sí, con el plan Enterprise puedes gestionar una red de tiendas desde un panel centralizado. Cada tienda tiene sus propios datos aislados.',
    faq5_q: '¿Qué divisas están admitidas?',
    faq5_a: 'HabaShop admite 6 divisas: Franco CFA de África Occidental (XOF), Franco CFA de África Central (XAF), Euro (EUR), Dólar US (USD), Dólar canadiense (CAD) y Libra Esterlina (GBP). La conversión es automática y el IVA es configurable por tienda.',
    cta_title: '¿Listo para modernizar tu negocio?',
    cta_sub: 'Únete a los comerciantes africanos que confían en HabaShop',
    cta_btn: 'Empezar ahora — Es gratis',
    cta_note: 'Sin tarjeta de crédito · 14 días de prueba gratuita',
    footer: '© 2026 HabaShop · Software SaaS para comercios africanos',
    footer_links: ['Privacidad', 'Términos', 'Contacto'],
    trust_title: 'Ya activos en 8+ países africanos',
    cur_title: 'Multi-divisa y Multi-idioma',
    cur_sub: 'Adaptado a tu mercado, en tu idioma',
    proof_stores: 'tiendas activas',
    proof_countries: '150+ países',
  },
  it: {
    nav: ['Funzioni', 'Prezzi', 'FAQ'],
    nav_features: 'Funzioni',
    nav_pricing: 'Prezzi',
    nav_faq: 'FAQ',
    nav_login: 'Accedi',
    badge: "Progettato per l'Africa francofona",
    h1a: 'Gestisci il tuo business',
    h1b: 'in modo semplice ed efficiente',
    hero_sub: 'HabaShop centralizza il tuo POS, magazzino, team e finanze in un unico strumento — semplice, veloce e disponibile anche senza internet.',
    cta1: 'Inizia gratis',
    cta2: 'Guarda la demo',
    stat1_l: 'Moduli integrati',
    stat2_l: 'Offline-ready',
    stat3_l: 'Valute supportate',
    stat4_l: 'Paesi target',
    features_label: 'FUNZIONI',
    features_title: 'Tutto ciò di cui hai bisogno',
    features_sub: '16 moduli integrati per gestire ogni aspetto del tuo business',
    feature1_title: 'Punto Vendita',
    feature1_desc: 'Incasso rapido, catalogo filtrabile, multi-pagamento, scontrino stampato o WhatsApp, modalità offline.',
    feature2_title: 'Magazzino & Inventario',
    feature2_desc: "Avvisi di esaurimento in tempo reale, CRUD prodotti, ordine automatico dalla scheda prodotto.",
    feature3_title: 'Report & Analisi',
    feature3_desc: 'KPI per periodo, fatturato, margini, top prodotti, ripartizione pagamenti. Export CSV e PDF in un clic.',
    feature4_title: 'CRM Clienti',
    feature4_desc: "Schede clienti, tipi (ingrosso/fedele), programma fedeltà e storico acquisti completo.",
    feature5_title: 'HR & Turni',
    feature5_desc: 'Schede dipendenti, turni settimanali drag & drop, gestione ferie e tracciamento presenze.',
    feature6_title: 'Sicurezza & RBAC',
    feature6_desc: 'Ruoli e permessi granulari, autenticazione 2FA TOTP, registro di audit immutabile, multi-tenant.',
    how_label: 'COME FUNZIONA',
    how_title: 'Inizia in 4 passi',
    step1_title: 'Crea il tuo negozio',
    step1_desc: 'Registrazione in 2 minuti. Configura il tuo spazio, aggiungi prodotti e team.',
    step2_title: 'Forma il tuo team',
    step2_desc: 'Interfaccia intuitiva. I tuoi cassieri padroneggiano il POS in meno di un ora.',
    step3_title: 'Vendi e gestisci',
    step3_desc: 'POS veloce, inventario in tempo reale, avvisi automatici, report istantanei.',
    step4_title: 'Analizza e cresci',
    step4_desc: 'Dashboard, esportazioni, tendenze prodotti. Prendi decisioni migliori ogni giorno.',
    testimonials_label: 'TESTIMONIANZE',
    testimonials_title: 'Si fidano di HabaShop',
    test1_name: 'Mamadou Diallo',
    test1_role: 'Grossista · Dakar',
    test1_quote: "Da quando uso HabaShop, ho visibilità totale sul mio magazzino. Gli avvisi di esaurimento mi hanno salvato più volte.",
    test2_name: 'Fatou Koné',
    test2_role: 'Alimentari · Abidjan',
    test2_quote: "Il POS è ultrarapido e funziona anche quando manca la connessione. Le mie cassiere sono state formate in 30 minuti.",
    test3_name: 'Ibrahim Touré',
    test3_role: 'Semi-grossista · Bamako',
    test3_quote: "I report di vendita mi aiutano a prendere decisioni d'acquisto migliori. L'interfaccia è chiara e i dati sono sempre aggiornati.",
    pricing_label: 'PREZZI',
    pricing_title: "Prezzi adattati per l'Africa",
    pricing_sub: '14 giorni di prova gratuita — nessuna carta richiesta',
    per_month: '/mese',
    on_estimate: 'Su preventivo',
    most_popular: 'Il più popolare',
    free_start: 'Inizia gratis',
    try_free: 'Prova 14 giorni',
    contact_us: 'Contattaci',
    starter_name: 'Starter',
    starter_sub: 'Per le piccole attività',
    business_name: 'Business',
    business_sub: "Per le attività in crescita",
    enterprise_name: 'Enterprise',
    enterprise_sub: 'Per le reti di negozi',
    feat_pos_1: 'POS (1 cassa)',
    feat_stock_500: 'Gestione magazzino (500 prodotti)',
    feat_reports: 'Report di base',
    feat_support: 'Supporto via email',
    feat_multiuser: 'Multi-utente',
    feat_hr: 'Modulo HR & Turni',
    feat_pos_3: 'POS (3 casse)',
    feat_stock_inf: 'Magazzino illimitato',
    feat_crm: 'CRM completo',
    feat_hr_full: 'HR, Turni, Paghe',
    feat_5users: '5 utenti inclusi',
    feat_priority: 'Supporto prioritario',
    feat_pos_inf: 'Casse illimitate',
    feat_multi_shop: 'Multi-negozio',
    feat_users_inf: 'Utenti illimitati',
    feat_api: 'API dedicata',
    feat_onboarding: 'Onboarding in loco',
    feat_sla: 'SLA garantito 99,9 %',
    faq_label: 'FAQ',
    faq_title: 'Domande frequenti',
    faq1_q: 'HabaShop funziona senza internet?',
    faq1_a: 'Sì! Il POS funziona offline grazie alla tecnologia PWA. Le vendite vengono salvate localmente e sincronizzate automaticamente al ripristino della connessione.',
    faq2_q: "Quanto tempo richiede l'installazione?",
    faq2_a: 'Nessuna installazione richiesta! HabaShop è un software web (SaaS). Ti connetti da qualsiasi browser. La configurazione iniziale richiede meno di 30 minuti.',
    faq3_q: 'Quanto costa HabaShop?',
    faq3_a: 'HabaShop offre una prova gratuita di 14 giorni. Il piano Starter costa 14 400 F CFA/mese, il piano Business 34 750 F CFA/mese, e il piano Enterprise è su preventivo.',
    faq4_q: 'Posso gestire più negozi?',
    faq4_a: 'Sì, con il piano Enterprise puoi gestire una rete di negozi da una dashboard centralizzata. Ogni negozio ha i propri dati isolati.',
    faq5_q: 'Quali valute sono supportate?',
    faq5_a: "HabaShop supporta 6 valute: Franco CFA dell'Africa Occidentale (XOF), Franco CFA dell'Africa Centrale (XAF), Euro (EUR), Dollaro US (USD), Dollaro canadese (CAD) e Sterlina britannica (GBP). La conversione è automatica e l'IVA è configurabile per negozio.",
    cta_title: 'Pronto a modernizzare il tuo business?',
    cta_sub: "Unisciti ai commercianti africani che si fidano di HabaShop",
    cta_btn: "Inizia ora — È gratis",
    cta_note: "Nessuna carta di credito richiesta · 14 giorni di prova gratuita",
    footer: '© 2026 HabaShop · Software SaaS per le attività africane',
    footer_links: ['Privacy', 'Termini', 'Contatto'],
    trust_title: 'Già attivi in 8+ paesi africani',
    cur_title: 'Multi-valuta & Multi-lingua',
    cur_sub: 'Adattato al tuo mercato, nella tua lingua',
    proof_stores: 'negozi attivi',
    proof_countries: '150+ paesi',
  },
}

// ─── DARK PALETTE ─────────────────────────────────────────────────────────────

export const D = {
  bg:      '#0A0C14',
  bg2:     '#0D1019',
  bg3:     '#11151F',
  bg4:     '#161C2B',
  p:       '#6C47FF',
  p2:      '#8B6FFF',
  p3:      '#A991FF',
  gold:    '#FFB020',
  gold2:   '#FFC53D',
  text:    '#EAEEF6',
  text2:   'rgba(234,238,246,.66)',
  text3:   'rgba(234,238,246,.65)',
  text4:   'rgba(234,238,246,.55)',
  border:  'rgba(255,255,255,.06)',
  border2: 'rgba(255,255,255,.11)',
  acc:     '#22C77A',
  acc2:    '#4F86F0',
  acc3:    '#FFB020',
  acc4:    '#FF5C72',
}

export const FONT = "'Geist Variable', 'Geist', system-ui, -apple-system, sans-serif"
export const MONO = "'JetBrains Mono', ui-monospace, SFMono-Regular, Menlo, monospace"

export const scrollTo = (id: string) => {
  document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
}

export type LandingT = typeof LANDING_TRANSLATIONS['fr']
